In [13]:
import numpy as np

In [14]:
import sklearn

In [15]:
import pandas

In [16]:
sales_data = pandas.read_csv('/home/fxs0528/train.csv')

In [17]:
from random import seed, sample
scale_data = sales_data.shape
sample_index = sample(range(0, scale_data[0]-1), int (0.8*(scale_data[0]-1)))

In [18]:
testing = sales_data.drop(sales_data.index[sample_index])
training = sales_data.ix[sample_index]

In [19]:
from sklearn.naive_bayes import MultinomialNB

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
raw_data = training.values.copy()
training_features = raw_data[:, -1]
training_data = raw_data[:, 1:-1]
raw_data = testing.values.copy()
testing_features = raw_data[:, -1]
testing_data = raw_data[:, 1:-1]
encoder = LabelEncoder()
y = encoder.fit_transform(training_features).astype(np.int32)
yy = encoder.fit_transform(testing_features).astype(np.int32)

In [22]:
nb_classifier = MultinomialNB()

In [23]:
nb_model = nb_classifier.fit(training_data, y)

In [24]:
from sklearn.metrics import confusion_matrix
res = nb_model.predict(testing_data)
m = confusion_matrix(res, yy)

In [25]:
m

array([[ 194,   13,   21,    1,    1,  153,   48,  311,   98],
       [  12, 2059,  599,  153,   14,    9,   22,    3,   12],
       [   3,  478,  448,   19,    3,   31,   40,   27,    1],
       [   3,  551,  466,  349,    0,   34,   49,    4,   10],
       [   1,   42,   19,    5,  506,    1,    2,    2,    0],
       [  17,    5,    2,    4,    1, 2390,   19,  100,   31],
       [  17,   34,   57,   12,    0,   76,  341,   39,    5],
       [  31,    1,    6,    1,    0,   49,   31, 1124,   16],
       [  93,   29,    4,   10,    2,  115,    5,   63,  830]])

In [29]:
np.matrix.trace(m).astype(np.float32) / testing_data.shape[0] 

0.66583178476205862

In [67]:
freq_vector = np.bincount(y)
freq_vector

array([ 1558, 12910,  6382,  2137,  2212, 11277,  2282,  6791,  3952])

In [68]:
prior_vector = freq_vector.astype(np.float32) / np.sum(freq_vector)

In [69]:
prior_vector

array([ 0.03147411,  0.26080281,  0.12892669,  0.04317084,  0.04468597,
        0.22781359,  0.04610008,  0.13718915,  0.07983677], dtype=float32)

In [70]:
nb_classifier_prior = MultinomialNB(fit_prior=True, class_prior=prior_vector)

In [71]:
nb_model_prior = nb_classifier_prior.fit(training_data, y)

In [72]:
res_prior = nb_model_prior.predict(testing_data)
m_prior = confusion_matrix(res, yy)

In [74]:
np.matrix.trace(m_prior).astype(np.float32) / testing_data.shape[0] 

0.66583178476205862